### ISSUE TITLE
Stepping

### ISSUE THREAD

**Issue by Opzon** [Wurst-Imperium/Wurst-Client-for-MC-1.10.X#10]
the client wants to always step up one block and step is disabled. No way to turn it off :(

This always occurs. It occurs when you walk next to a block just like the step hack. To recreate it just walk against a block (1 block) and it should make you step up it for no reason even when step is disabled.

**Comment by boomer00oo** [comment]
Please provide more detail. Does this always happen? When does it happen? Is it possible to recreate? Etc.

**Comment by Opzon** [comment]
@boomer00oo edited post.

**Comment by vovanre** [comment]
https://youtu.be/yoe2GhBt86I?t=31s

**Comment by Opzon** [comment]
@vovanre oh.... wow. Thanks haha! <3
